// Code generated by Slice Machine. DO NOT EDIT.
import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  big_section: dynamic(() => import("./TabSection")),
  hero: dynamic(() => import("./Hero")),
};
